export interface CanonicalError {
  className: string;
  code: string;
  httpStatus?: number;
  description: string;
  data?: { name: string; type: string; description?: string }[];
  reasonValues?: string[];
  domain: string;
  group: string;
  thrownBy: string[];
}

const B2B_AUTHENTICATED_ACTIONS = [
  'b2b/organization/get-memberships',
  'b2b/organization/switch',
  'b2b/organization/set-login-preferences',
  'b2b/organization/employee-invite',
  'b2b/organization/employee-update',
  'b2b/organization/employee-delete',
  'b2b/organization/role-get-all',
  'b2b/organization/role-create',
  'b2b/organization/role-update',
  'b2b/organization/role-delete',
  'b2b/organization/address-get-all',
  'b2b/organization/address-create',
  'b2b/organization/address-update',
  'b2b/organization/address-delete',
  'b2b/organization/address-set-default',
  'b2b/organization/cost-center-create',
  'b2b/organization/cost-center-update',
  'b2b/organization/cost-center-delete',
  'b2b/organization/budget-create',
  'b2b/organization/budget-update',
  'b2b/organization/budget-delete',
  'b2b/organization/product-number-get-all',
  'b2b/organization/product-number-set',
  'b2b/organization/product-number-delete',
  'b2b/quote/request',
  'b2b/quote/accept',
  'b2b/quote/decline',
  'b2b/quote/request-change',
  'b2b/quote/cancel',
  'b2b/quote/get-checkout-url',
  'b2b/approval-flow/decide',
  'b2b/cart/share-set',
  'b2b/cart/share-get-all',
  'b2b/cart/share-delete',
];

const B2B_ORGANIZATION_PROTECTED_ACTIONS = B2B_AUTHENTICATED_ACTIONS.filter(
  (action) =>
    ![
      'b2b/organization/get-memberships',
      'b2b/organization/switch',
      'b2b/organization/set-login-preferences',
      'b2b/quote/request',
      'b2b/quote/accept',
      'b2b/quote/decline',
      'b2b/quote/request-change',
      'b2b/quote/cancel',
      'b2b/quote/get-checkout-url',
    ].includes(action)
);

export const canonicalErrors: CanonicalError[] = [
  // ── Auth ──────────────────────────────────────────────────
  {
    className: 'InvalidCredentialsError',
    code: 'AUTH_INVALID_CREDENTIALS',
    httpStatus: 401,
    description: 'Thrown when authentication with the provided credentials fails.',
    domain: 'ecommerce',
    group: 'Auth',
    thrownBy: ['ecommerce/auth/login', 'ecommerce/product/reviews/create'],
  },
  {
    className: 'UnauthenticatedError',
    code: 'AUTH_UNAUTHENTICATED',
    httpStatus: 401,
    description: 'Thrown when the user tries to access a resource that requires authentication.',
    domain: 'ecommerce',
    group: 'Auth',
    thrownBy: [
      ...B2B_AUTHENTICATED_ACTIONS,
      'ecommerce/customer/get-current',
      'ecommerce/customer/update',
      'ecommerce/customer/address-get-all',
      'ecommerce/customer/address-create',
      'ecommerce/customer/address-update',
      'ecommerce/customer/address-delete',
      'ecommerce/customer/address-set-default',
      'ecommerce/order/reorder',
      'ecommerce/order/cancel',
      'ecommerce/order/get-statistics',
      'ecommerce/document/get-all',
      'ecommerce/document/get-download-url',
      'ecommerce/product-list/create',
      'ecommerce/product-list/update',
      'ecommerce/product-list/delete',
      'ecommerce/product-list/duplicate',
      'ecommerce/product-list/add-items',
      'ecommerce/product-list/update-items',
      'ecommerce/product-list/remove-items',
      'ecommerce/product-list/add-to-cart',
    ],
  },
  {
    className: 'CustomerDisabledError',
    code: 'AUTH_CUSTOMER_DISABLED',
    httpStatus: 403,
    description: 'Thrown when a customer that is trying to login is disabled.',
    domain: 'ecommerce',
    group: 'Auth',
    thrownBy: [],
  },

  // ── Cart ──────────────────────────────────────────────────
  {
    className: 'ProductNotFoundError',
    code: 'CART_PRODUCT_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when a product that should be added to the cart is not found.',
    data: [{ name: 'variantId', type: 'string' }],
    domain: 'ecommerce',
    group: 'Cart',
    thrownBy: ['ecommerce/cart/add-items', 'ecommerce/product-list/add-items', 'b2b/organization/product-number-set'],
  },
  {
    className: 'ProductStockError',
    code: 'CART_PRODUCT_STOCK_ERROR',
    description: 'Thrown when a product cannot be added to the cart due to stock issues.',
    data: [
      { name: 'variantId', type: 'string' },
      { name: 'reason', type: 'ProductStockErrorReason' },
    ],
    reasonValues: ['OUT_OF_STOCK', 'NOT_ENOUGH_STOCK'],
    domain: 'ecommerce',
    group: 'Cart',
    thrownBy: ['ecommerce/cart/add-items'],
  },
  {
    className: 'ProductQuantityError',
    code: 'CART_PRODUCT_QUANTITY_ERROR',
    description: 'Thrown when an item cannot be added to the cart due to quantity constraints.',
    data: [
      { name: 'variantId', type: 'string' },
      { name: 'reason', type: 'ProductQuantityErrorReason' },
    ],
    reasonValues: ['MINIMUM_NOT_MET', 'MAXIMUM_EXCEEDED', 'INVALID_INCREMENT'],
    domain: 'ecommerce',
    group: 'Cart',
    thrownBy: ['ecommerce/cart/add-items'],
  },
  {
    className: 'DiscountCodeNotFoundError',
    code: 'CART_DISCOUNT_CODE_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when a discount code that should be added to the cart is not found.',
    data: [{ name: 'code', type: 'string' }],
    domain: 'ecommerce',
    group: 'Cart',
    thrownBy: ['ecommerce/cart/add-items'],
  },
  {
    className: 'DiscountCodeNotRedeemableError',
    code: 'CART_DISCOUNT_CODE_NOT_REDEEMABLE',
    description: 'Thrown when a discount code cannot be applied to the cart.',
    data: [
      { name: 'code', type: 'string' },
      { name: 'reason', type: 'DiscountCodeNotRedeemableErrorReason' },
    ],
    reasonValues: [
      'CODE_NOT_HONOURED',
      'CURRENTLY_INACTIVE',
      'CUSTOMER_NOT_ELIGIBLE',
      'CUSTOMER_USAGE_LIMIT_REACHED',
      'ELIGIBLE_CUSTOMER_MISSING',
      'INCOMPATIBLE_PURCHASE_TYPE',
      'NO_ENTITLED_LINE_ITEMS',
      'NO_ENTITLED_SHIPPING_LINES',
      'PURCHASE_NOT_IN_RANGE',
      'QUANTITY_NOT_IN_RANGE',
      'USAGE_LIMIT_REACHED',
      'OTHER',
    ],
    domain: 'ecommerce',
    group: 'Cart',
    thrownBy: ['ecommerce/cart/add-items'],
  },

  // ── Customer ──────────────────────────────────────────────
  {
    className: 'AddressNotFoundError',
    code: 'CUSTOMER_ADDRESS_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when an address with the given ID is not found.',
    data: [{ name: 'id', type: 'string' }],
    domain: 'ecommerce',
    group: 'Customer',
    thrownBy: ['ecommerce/customer/address-update', 'ecommerce/customer/address-delete', 'ecommerce/customer/address-set-default'],
  },
  {
    className: 'InvalidFieldError',
    code: 'INVALID_FIELD',
    description:
      'Thrown when a field in the input is invalid. Use for backend-system validation errors when no more specific error applies.',
    data: [
      { name: 'reason', type: 'InvalidFieldErrorReason' },
      { name: 'field', type: 'string[]', description: 'Path to the invalid field' },
    ],
    reasonValues: ['MISSING', 'TOO_LONG', 'TOO_SHORT', 'INVALID_FORMAT', 'INVALID_VALUE'],
    domain: 'ecommerce',
    group: 'Customer',
    thrownBy: [
      'ecommerce/auth/register',
      'ecommerce/customer/update',
      'ecommerce/customer/address-create',
      'ecommerce/customer/address-update',
      'ecommerce/product/reviews/create',
      'ecommerce/product-list/create',
      'ecommerce/product-list/update',
      'b2b/cart/share-set',
      'b2b/organization/address-create',
      'b2b/organization/address-update',
      'b2b/organization/budget-create',
      'b2b/organization/budget-update',
      'b2b/organization/cost-center-create',
      'b2b/organization/cost-center-update',
      'b2b/organization/employee-invite',
      'b2b/organization/employee-update',
      'b2b/organization/product-number-set',
      'b2b/organization/role-create',
    ],
  },

  // ── Product ───────────────────────────────────────────────
  {
    className: 'CategoryNotFoundError',
    code: 'CATEGORY_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when a category with the given ID is not found.',
    data: [{ name: 'id', type: 'string' }],
    domain: 'ecommerce',
    group: 'Product',
    thrownBy: [],
  },

  // ── Product Lists ─────────────────────────────────────────
  {
    className: 'ProductListNotFoundError',
    code: 'PRODUCT_LIST_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when a product list is not found or is not visible to the current customer.',
    data: [{ name: 'id', type: 'string' }],
    domain: 'ecommerce',
    group: 'Product lists',
    thrownBy: [
      'ecommerce/product-list/update',
      'ecommerce/product-list/delete',
      'ecommerce/product-list/duplicate',
      'ecommerce/product-list/add-items',
      'ecommerce/product-list/update-items',
      'ecommerce/product-list/remove-items',
      'ecommerce/product-list/add-to-cart',
    ],
  },
  {
    className: 'ProductListItemNotFoundError',
    code: 'PRODUCT_LIST_ITEM_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when a product is not present on the specified product list.',
    data: [
      { name: 'id', type: 'string', description: 'Product-list ID' },
      { name: 'productId', type: 'string' },
      { name: 'variantId', type: 'string' },
    ],
    domain: 'ecommerce',
    group: 'Product lists',
    thrownBy: ['ecommerce/product-list/update-items', 'ecommerce/product-list/remove-items'],
  },

  // ── Orders and documents ──────────────────────────────────
  {
    className: 'OrderNotFoundError',
    code: 'ORDER_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when an order is not found or is not visible to the current customer.',
    data: [{ name: 'id', type: 'string' }],
    domain: 'ecommerce',
    group: 'Orders',
    thrownBy: ['ecommerce/order/reorder', 'ecommerce/order/cancel'],
  },
  {
    className: 'OrderNotCancellableError',
    code: 'ORDER_NOT_CANCELLABLE',
    description: 'Thrown when the current order state does not allow cancellation.',
    data: [
      { name: 'id', type: 'string' },
      { name: 'status', type: 'WellKnownOrderStatus' },
    ],
    domain: 'ecommerce',
    group: 'Orders',
    thrownBy: ['ecommerce/order/cancel'],
  },
  {
    className: 'DocumentNotFoundError',
    code: 'DOCUMENT_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when a document is not found or is not visible to the current customer.',
    data: [{ name: 'id', type: 'string' }],
    domain: 'ecommerce',
    group: 'Documents',
    thrownBy: ['ecommerce/document/get-download-url'],
  },

  // ── B2B organization ──────────────────────────────────────
  {
    className: 'NoOrganizationContextError',
    code: 'ORGANIZATION_NO_CONTEXT',
    description: 'Thrown when the current customer has no selected B2B organization context.',
    domain: 'b2b',
    group: 'Organization',
    thrownBy: B2B_ORGANIZATION_PROTECTED_ACTIONS,
  },
  {
    className: 'OrganizationNotFoundError',
    code: 'ORGANIZATION_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when an organization is not found or the current customer is not a member.',
    data: [{ name: 'id', type: 'string' }],
    domain: 'b2b',
    group: 'Organization',
    thrownBy: ['b2b/organization/switch', 'b2b/organization/set-login-preferences'],
  },
  {
    className: 'PermissionDeniedError',
    code: 'ORGANIZATION_PERMISSION_DENIED',
    httpStatus: 403,
    description: 'Thrown when the employee lacks the permission required for an organization operation.',
    data: [{ name: 'permission', type: 'string' }],
    domain: 'b2b',
    group: 'Organization',
    thrownBy: B2B_ORGANIZATION_PROTECTED_ACTIONS,
  },
  {
    className: 'EmployeeNotFoundError',
    code: 'EMPLOYEE_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when an employee is not found in the current organization.',
    data: [{ name: 'id', type: 'string' }],
    domain: 'b2b',
    group: 'Employees and roles',
    thrownBy: ['b2b/organization/employee-update', 'b2b/organization/employee-delete', 'b2b/cart/share-set'],
  },
  {
    className: 'EmployeeAlreadyExistsError',
    code: 'EMPLOYEE_ALREADY_EXISTS',
    description: 'Thrown when an invited email already belongs to an employee of the organization.',
    data: [{ name: 'email', type: 'string' }],
    domain: 'b2b',
    group: 'Employees and roles',
    thrownBy: ['b2b/organization/employee-invite'],
  },
  {
    className: 'EmployeeNotDeletableError',
    code: 'EMPLOYEE_NOT_DELETABLE',
    description: 'Thrown when an employee cannot be deleted and must be deactivated instead.',
    data: [{ name: 'id', type: 'string' }],
    domain: 'b2b',
    group: 'Employees and roles',
    thrownBy: ['b2b/organization/employee-delete'],
  },
  {
    className: 'RoleNotFoundError',
    code: 'ROLE_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when an organization role is not found.',
    data: [{ name: 'id', type: 'string' }],
    domain: 'b2b',
    group: 'Employees and roles',
    thrownBy: ['b2b/organization/role-update', 'b2b/organization/role-delete'],
  },
  {
    className: 'RoleNotModifiableError',
    code: 'ROLE_NOT_MODIFIABLE',
    description: 'Thrown when a protected or system role cannot be updated or deleted.',
    data: [{ name: 'id', type: 'string' }],
    domain: 'b2b',
    group: 'Employees and roles',
    thrownBy: ['b2b/organization/role-update', 'b2b/organization/role-delete'],
  },
  {
    className: 'OrganizationAddressNotFoundError',
    code: 'ORGANIZATION_ADDRESS_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when an organization address is not found.',
    data: [{ name: 'id', type: 'string' }],
    domain: 'b2b',
    group: 'Organization resources',
    thrownBy: ['b2b/organization/address-update', 'b2b/organization/address-delete', 'b2b/organization/address-set-default'],
  },
  {
    className: 'CostCenterNotFoundError',
    code: 'COST_CENTER_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when a cost center is not found.',
    data: [{ name: 'id', type: 'string' }],
    domain: 'b2b',
    group: 'Organization resources',
    thrownBy: ['b2b/organization/cost-center-update', 'b2b/organization/cost-center-delete'],
  },
  {
    className: 'BudgetNotFoundError',
    code: 'BUDGET_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when a budget is not found.',
    data: [{ name: 'id', type: 'string' }],
    domain: 'b2b',
    group: 'Organization resources',
    thrownBy: ['b2b/organization/budget-update', 'b2b/organization/budget-delete'],
  },
  {
    className: 'ProductNumberNotFoundError',
    code: 'PRODUCT_NUMBER_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when a variant has no customer-specific product-number mapping.',
    data: [{ name: 'variantId', type: 'string' }],
    domain: 'b2b',
    group: 'Organization resources',
    thrownBy: ['b2b/organization/product-number-delete'],
  },

  // ── B2B quotes and approvals ──────────────────────────────
  {
    className: 'QuoteNotFoundError',
    code: 'QUOTE_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when a quote is not found or is not visible to the current customer.',
    data: [{ name: 'id', type: 'string' }],
    domain: 'b2b',
    group: 'Quotes',
    thrownBy: ['b2b/quote/accept', 'b2b/quote/decline', 'b2b/quote/request-change', 'b2b/quote/cancel', 'b2b/quote/get-checkout-url'],
  },
  {
    className: 'QuoteStateError',
    code: 'QUOTE_INVALID_STATE',
    description: 'Thrown when a quote state does not allow the requested operation.',
    data: [
      { name: 'id', type: 'string' },
      { name: 'status', type: 'WellKnownQuoteStatus' },
    ],
    domain: 'b2b',
    group: 'Quotes',
    thrownBy: ['b2b/quote/accept', 'b2b/quote/decline', 'b2b/quote/request-change', 'b2b/quote/cancel', 'b2b/quote/get-checkout-url'],
  },
  {
    className: 'QuoteExpiredError',
    code: 'QUOTE_EXPIRED',
    description: 'Thrown when the quote validity period has ended.',
    data: [
      { name: 'id', type: 'string' },
      { name: 'validUntil', type: 'string' },
    ],
    domain: 'b2b',
    group: 'Quotes',
    thrownBy: ['b2b/quote/accept'],
  },
  {
    className: 'EmptyCartError',
    code: 'CART_EMPTY',
    description: 'Thrown when requesting a quote from an empty cart.',
    domain: 'b2b',
    group: 'Quotes',
    thrownBy: ['b2b/quote/request'],
  },
  {
    className: 'ApprovalNotFoundError',
    code: 'APPROVAL_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when an approval request is not found or is not visible to the current employee.',
    data: [{ name: 'id', type: 'string' }],
    domain: 'b2b',
    group: 'Approval flows',
    thrownBy: ['b2b/approval-flow/decide'],
  },
  {
    className: 'ApprovalStateError',
    code: 'APPROVAL_INVALID_STATE',
    description: 'Thrown when an approval request state does not allow the decision.',
    data: [
      { name: 'id', type: 'string' },
      { name: 'status', type: 'ApprovalFlowStatus' },
    ],
    domain: 'b2b',
    group: 'Approval flows',
    thrownBy: ['b2b/approval-flow/decide'],
  },
  {
    className: 'CartShareNotFoundError',
    code: 'CART_SHARE_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when the current cart is not shared with the specified employee.',
    data: [{ name: 'employeeId', type: 'string' }],
    domain: 'b2b',
    group: 'Cart sharing',
    thrownBy: ['b2b/cart/share-delete'],
  },

  // ── Blog ──────────────────────────────────────────────────
  {
    className: 'BlogCollectionBySlugNotFoundError',
    code: 'BLOG_COLLECTION_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when a blog collection with the given slug is not found.',
    data: [{ name: 'slug', type: 'string' }],
    domain: 'blog',
    group: 'Collection',
    thrownBy: [],
  },
  {
    className: 'BlogPostBySlugNotFoundError',
    code: 'BLOG_POST_NOT_FOUND',
    httpStatus: 404,
    description: 'Thrown when a blog post with the given slug is not found.',
    data: [{ name: 'slug', type: 'string' }],
    domain: 'blog',
    group: 'Post',
    thrownBy: [],
  },
];
